backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: amrs german
    label: AMRs Deutsch
    folder: "_content/amrs_de"
    extension: "mdx"
    format: "frontmatter"
    identifier_field: name
    create: true
    fields:
      - name: name
        label: Name
        widget: string
      - name: body
        label: Inhalt
        widget: markdown
      - name: image
        label: Bild
        widget: image

  - name: amrs english
    label: AMRs Englisch
    folder: "_content/amrs_en"
    extension: "mdx"
    format: "frontmatter"
    identifier_field: name
    create: true
    fields:
      - name: name
        label: Name
        widget: string
      - name: body
        label: Inhalt
        widget: markdown
      - name: image
        label: Bild
        widget: image
  
  - name: videos german
    label: Videos Deutsch
    folder: "_content/videos_de"
    extension: "mdx"
    format: "frontmatter"
    create: true
    fields:
      - name: title
        label: Titel
        widget: string
      - name: thumbnail
        label: Thumbnail
        widget: image
      - name: url
        label: URL
        widget: string
      - name: body
        label: Inhalt
        widget: markdown
  - name: videos english
    label: Videos Englisch
    folder: "_content/videos_en"
    extension: "mdx"
    format: "frontmatter"
    create: true
    fields:
      - name: title
        label: Titel
        widget: string
      - name: thumbnail
        label: Thumbnail
        widget: image
      - name: url
        label: URL
        widget: string
      - name: body
        label: Inhalt
        widget: markdown

  - name: events
    label: Events
    folder: "_content/events"
    extension: "mdx"
    format: "frontmatter"
    create: true
    fields:
      - name: title
        label: Titel
        widget: string
      - name: date
        label: Zeitpunkt
        widget: datetime
      - name: image
        label: Bild
        widget: image
      - name: body
        label: Inhalt
        widget: markdown

  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: true
    files:
      - name: "frontpage_de"
        label: "Frontpage"
        file: "meta/frontpage.de.yml"
        description: "Frontpage data de"
        fields:
          - name: page_description
            label: Meta Text
            widget: text
          - name: bulletpoints
            label: Bulletpoints
            label_singular: Bulletpoint
            widget: list
            fields:
              - name: text
                widget: "string"
                hint: A frontpage bullet point
          - name: headline
            label: Page Headline
            widget: string
          - name: introduction_text
            label: Intro text
            widget: text
          - name: trial_kit_url
            label: Trialkit URL
            widget: string
          - name: trial_kit_label
            label: Trialkit Label
            widget: string
          - name: trial_kit_description
            label: Trialkit Description
            widget: text
          - name: contact_url
            label: Contact URL
            widget: string
          - name: contact_label
            label: Contact Label
            widget: string
          - name: contact_description
            label: Contact Description
            widget: text
          - name: video_url
            label: Video URL
            widget: file
          - name: video_title
            label: Video Title
            widget: string
          - name: video_subtext
            label: Video Subtext
            widget: text
          - name: mail_address
            label: Mail Addresse
            widget: string
          - name: mail_subject
            label: Mail Betreff
            widget: string
          - name: mail_body
            label: Mail Inhalt
            widget: text
          - name: amr_headline
            label: AMR Section Headline
            widget: string
          - name: amr_subtext
            label: AMR Section Subtext
            widget: text


      - name: "frontpage_en"
        label: "Frontpage Englisch"
        file: "meta/frontpage.en.yml"
        description: "Frontpage data en"
        fields:
          - name: page_description
            label: Meta Text
            widget: text
          - name: bulletpoints
            label: Bulletpoints
            label_singular: Bulletpoint
            widget: list
            fields:
              - name: text
                widget: "string"
                hint: A frontpage bullet point
          - name: headline
            label: Page Headline
            widget: string
          - name: introduction_text
            label: Intro text
            widget: text
          - name: trial_kit_url
            label: Trialkit URL
            widget: string
          - name: trial_kit_label
            label: Trialkit Label
            widget: string
          - name: trial_kit_description
            label: Trialkit Description
            widget: text
          - name: contact_url
            label: Contact URL
            widget: string
          - name: contact_label
            label: Contact Label
            widget: string
          - name: contact_description
            label: Contact Description
            widget: text
          - name: video_url
            label: Video URL
            widget: file
          - name: video_title
            label: Video Title
            widget: string
          - name: video_subtext
            label: Video Subtext
            widget: text
          - name: mail_address
            label: Mail Addresse
            widget: string
          - name: mail_subject
            label: Mail Betreff
            widget: string
          - name: mail_body
            label: Mail Inhalt
            widget: text
          - name: amr_headline
            label: AMR Section Headline
            widget: string
          - name: amr_subtext
            label: AMR Section Subtext
            widget: text

