backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: amrs german
    label: AMRs Deutsch
    folder: "_content/amrs_de"
    extension: "mdx"
    format: "frontmatter"
    identifier_field: name
    create: true
    fields:
      - name: name
        label: Name
        widget: string
      - name: body
        label: Inhalt
        widget: markdown
      - name: image
        label: Bild
        widget: image
      - name: max_speed
        label: max Speed with unit
        widget: string
      - name: weight
        label: weight with unit
        widget: string
      - name: drive_type
        label: Drive Type/ Antriebsart
        widget: string
      - name: operation_time
        label: Operation Time with unit
        widget: string
      - name: charging_speed
        label: Charging Time with unit
        widget: string
      - name: payload
        label: Payload with unit
        widget: string

  - name: amrs english
    label: AMRs Englisch
    folder: "_content/amrs_en"
    extension: "mdx"
    format: "frontmatter"
    identifier_field: name
    create: true
    fields:
      - name: name
        label: Name
        widget: string
      - name: body
        label: Inhalt
        widget: markdown
      - name: image
        label: Bild
        widget: image
      - name: max_speed
        label: max Speed with unit
        widget: string
      - name: weight
        label: weight with unit
        widget: string
      - name: drive_type
        label: Drive Type/ Antriebsart
        widget: string
      - name: operation_time
        label: Operation Time with unit
        widget: string
      - name: charging_speed
        label: Charging Speed with unit
        widget: string
      - name: payload
        label: Payload with unit
        widget: string
  
  - name: videos german
    label: Videos Deutsch
    folder: "_content/videos_de"
    extension: "mdx"
    format: "frontmatter"
    create: true
    fields:
      - name: title
        label: Titel
        widget: string
      - name: thumbnail
        label: Thumbnail
        widget: image
      - name: url
        label: URL
        widget: string
      - name: body
        label: Inhalt
        widget: markdown
  - name: videos english
    label: Videos Englisch
    folder: "_content/videos_en"
    extension: "mdx"
    format: "frontmatter"
    create: true
    fields:
      - name: title
        label: Titel
        widget: string
      - name: thumbnail
        label: Thumbnail
        widget: image
      - name: url
        label: URL
        widget: string
      - name: body
        label: Inhalt
        widget: markdown

  - name: events
    label: Events
    folder: "_content/events"
    extension: "mdx"
    format: "frontmatter"
    create: true
    fields:
      - name: title
        label: Titel
        widget: string
      - name: date
        label: Zeitpunkt
        widget: datetime
      - name: image
        label: Bild
        widget: image
      - name: body
        label: Inhalt
        widget: markdown

  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: true
    files:
      - name: "frontpage_de"
        label: "Frontpage Deutsch"
        file: "meta/frontpage.de.yml"
        description: "Frontpage data de"
        fields:
          - name: page_description
            label: Meta Text
            widget: text
          - name: bulletpoints
            label: Bulletpoints
            label_singular: Bulletpoint
            widget: list
            fields:
              - name: text
                widget: "string"
                hint: A frontpage bullet point
          - name: headline
            label: Page Headline
            widget: string
          - name: introduction_text
            label: Intro text
            widget: text
          - name: trial_kit_url
            label: Trialkit URL
            widget: string
          - name: trial_kit_label
            label: Trialkit Label
            widget: string
          - name: trial_kit_description
            label: Trialkit Description
            widget: text
          - name: contact_url
            label: Contact URL
            widget: string
          - name: contact_label
            label: Contact Label
            widget: string
          - name: contact_description
            label: Contact Description
            widget: text
          - name: video_url
            label: Video URL
            widget: file
          - name: video_title
            label: Video Title
            widget: string
          - name: video_subtext
            label: Video Subtext
            widget: text
          - name: mail_address
            label: Mail Addresse
            widget: string
          - name: mail_subject
            label: Mail Betreff
            widget: string
          - name: mail_body
            label: Mail Inhalt
            widget: text
          - name: amr_headline
            label: AMR Section Headline
            widget: string
          - name: amr_subtext
            label: AMR Section Subtext
            widget: text


      - name: "frontpage_en"
        label: "Frontpage Englisch"
        file: "meta/frontpage.en.yml"
        description: "Frontpage data en"
        fields:
          - name: page_description
            label: Meta Text
            widget: text
          - name: bulletpoints
            label: Bulletpoints
            label_singular: Bulletpoint
            widget: list
            fields:
              - name: text
                widget: "string"
                hint: A frontpage bullet point
          - name: headline
            label: Page Headline
            widget: string
          - name: introduction_text
            label: Intro text
            widget: text
          - name: trial_kit_url
            label: Trialkit URL
            widget: string
          - name: trial_kit_label
            label: Trialkit Label
            widget: string
          - name: trial_kit_description
            label: Trialkit Description
            widget: text
          - name: contact_url
            label: Contact URL
            widget: string
          - name: contact_label
            label: Contact Label
            widget: string
          - name: contact_description
            label: Contact Description
            widget: text
          - name: video_url
            label: Video URL
            widget: file
          - name: video_title
            label: Video Title
            widget: string
          - name: video_subtext
            label: Video Subtext
            widget: text
          - name: mail_address
            label: Mail Addresse
            widget: string
          - name: mail_subject
            label: Mail Betreff
            widget: string
          - name: mail_body
            label: Mail Inhalt
            widget: text
          - name: amr_headline
            label: AMR Section Headline
            widget: string
          - name: amr_subtext
            label: AMR Section Subtext
            widget: text

      - name: "amr_page_de"
        label: "AMR Page Deutsch"
        file: "meta/amrpage.de.yml"
        description: "AMR page Labels de"
        fields:
          - name: headline_facts
            label: Headline for Facts
            widget: string
          - name: headline_usage
            label: Headline for Usage
            widget: string
          - name: max_speed_lbl
            label: Label for max Speed
            widget: string
          - name: weight_lbl
            label: Label for AMR weight
            widget: string
          - name: drive_type_lbl
            label: Label for drive Type
            widget: string
          - name: operation_time_lbl
            label: Label for Operation Time
            widget: string
          - name: charging_speed_lbl
            label: Label for charging Speed
            widget: string
          - name: payload_lbl
            label: Label for Payload
            widget: string

      - name: "amr_page_en"
        label: "AMR Page English"
        file: "meta/amrpage.en.yml"
        description: "AMR page Labels en"
        fields:
          - name: headline_facts
            label: Headline for Facts
            widget: string
          - name: headline_usage
            label: Headline for Usage
            widget: string
          - name: max_speed_lbl
            label: Label for max Speed
            widget: string
          - name: weight_lbl
            label: Label for AMR weight
            widget: string
          - name: drive_type_lbl
            label: Label for drive Type
            widget: string
          - name: operation_time_lbl
            label: Label for Operation Time
            widget: string
          - name: charging_speed_lbl
            label: Label for charging Speed
            widget: string
          - name: payload_lbl
            label: Label for Payload
            widget: string

      - name: "footer_de"
        label: "Footer Deutsch"
        file: "meta/footer.de.yml"
        description: "Footer de"
        fields:
          - name: header
            label: Header
            widget: string
          - name: contact_label
            label: Contact Label
            widget: string
          - name: contact_url
            label: Contact URL
            widget: string
          - name: data_protection_label
            label: Data Protection Label
            widget: string
          - name: data_protection_url
            label: Data Protection URL
            widget: string
          - name: legal_notice_label
            label: Legal Notice Label
            widget: string
          - name: legal_notice_url
            label: Legal Notice URL
            widget: string
          - name: faq_label
            label: FAQ Label
            widget: string
          - name: faq_url
            label: FAQ URL
            widget: string
          - name: copyright
            label: Copy Right
            widget: string
          - name: goto_top_url
            label: Goto Top URL
            widget: string

      - name: "footer_en"
        label: "Footer English"
        file: "meta/footer.en.yml"
        description: "Footer en"
        fields:
          - name: header
            label: Header
            widget: string
          - name: contact_label
            label: Contact Label
            widget: string
          - name: contact_url
            label: Contact URL
            widget: string
          - name: data_protection_label
            label: Data Protection Label
            widget: string
          - name: data_protection_url
            label: Data Protection URL
            widget: string
          - name: legal_notice_label
            label: Legal Notice Label
            widget: string
          - name: legal_notice_url
            label: Legal Notice URL
            widget: string
          - name: faq_label
            label: FAQ Label
            widget: string
          - name: faq_url
            label: FAQ URL
            widget: string
          - name: copyright
            label: Copy Right
            widget: string
          - name: goto_top_url
            label: Goto Top URL
            widget: string
