backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: true
    files:
      - name: "frontpage"
        label: "Frontpage"
        file: "meta/frontpage.yml"
        description: "Frontpage data"
        fields:
          - name: headline
            label: Headline
            widget: string
          - label: "Logo image"
            name: logo_url
            widget: "image"
            choose_url: true
          - label: "Logo image alternative text"
            name: logo_alt
            widget: "string"
            choose_url: true
          - name: bulletpoints
            label: Bulletpoints
            label_singular: Bulletpoint
            widget: list
            fields:
              - name: text
                widget: "string"
                hint: A frontpage bullet point

